name: Release
on:
  push:
    branches:
      - "!**/*"
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: setup tools
      run: |
        go get -v github.com/mitchellh/gox@v1.0.1
        curl -sL https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz | tar zxvf - && install ghr_v0.13.0_linux_amd64/ghr ~/go/bin/
    - name: packages
      run: PATH=~/go/bin:$PATH make packages
      env:
        CGO_ENABLED: 0

    - name: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: PATH=~/go/bin:$PATH make release

    - uses: actions/checkout@v1
    - name: clone homebrew-tap repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/mashiike/homebrew-tap

    - name: setup maltmil
      run: go get github.com/Songmu/maltmill/cmd/maltmill

    - name: update tap
      run: cd homebrew-tap && git switch -c feature/update-github-workflow-brew-tap-${GITHUB_RUN_ID} && PATH=~/go/bin:$PATH make releases/github-workflow-brew-tap && git add . && git push origin feature/update-github-workflow-brew-tap-${GITHUB_RUN_ID}
